version: "3"
services:
  database:
    image: 'postgres'
    ports: 
      - 5432:5432
    environment: 
      POSTGRES_PASSWORD: 'password'
    
  backend:
    build:
      context: './'
      dockerfile: 'Dockerfile'
    ports: 
      - 3333:3333
    depends_on: 
      - database
  